apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-echo-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kiukairor/go-echo
    targetRevision: main
    path: infra/helm/go-echo
    helm:
      valueFiles:
        - values.yaml
        - values-laberry-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
